{% set name = "fdb" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71395e3de90ef3bc6c518f6791a00d1ef76b50ddf4d8b2b4ac5f4f53d3dcbcc7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - future >=0.16.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - fdb

about:
  home: https://www.firebirdsql.org/en/devel-python-driver/
  license: BSD
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The Python driver for Firebird
  doc_url: http://fdb.readthedocs.io/en/v2.0/
  dev_url: https://github.com/FirebirdSQL/fdb

extra:
  recipe-maintainers:
    - m-rossi
