{% set name = "fdb" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59530dbddde830f3edd7ac66b0449c72fcc04a4c0deeb8d08320f3309eba1b91

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - fdb
  commands:
    - pip check

about:
  home: https://www.firebirdsql.org/en/devel-python-driver/
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: The Python driver for Firebird
  doc_url: http://fdb.readthedocs.io/en/v2.0/
  dev_url: https://github.com/FirebirdSQL/fdb

extra:
  recipe-maintainers:
    - m-rossi
