travis:
  secure:
    BINSTAR_TOKEN: cbU6Mr4LEZBp0nTPEWtZVZkbQs7P32OHLuVzCHYuXkG+ted7pYHrxIp5lux/wYyawF5z2oCRmZq4hfIGK9Y/wzuSNvG+EUKyLJ7QtLQEPWAAv4POtnxkRCizkR+mDwvX0GGhuqjN5vaiDZeUlN6tMYeJYE0aG30iD9sS58qG35gqUjCnWDMU8oWm2AXStl/YSLIg/SWmJ9vdKWvJpv9HdApWFVwKi8WpUBQ5As2hPafYGV5wLC/e0vzgmU1iOMe+YAgjHH4SPWRqawDpRir/JmvrmCTT2Z629m9CPLt4dVERu8j56umQhXK+Bou/LOdbD4BaaxtnwC1BJxG1jLlZLNwuxu4b74hBrYQ5p7gzoSo3dwrNCHnv2fPTkux31Q/AJeXkBSt+tutRTMNULB/deJc4p0WJein8gKdnrsbGyrO4OMKXLM2FKCTN1td2F88ZxUU+G4fdtbp+q4BHG3xYQHqlV+xJeBmZUe0RMwp2LgYfTjm5bHcOeLBZ3UjFNZDZB7VoeUWPTsKdIXbR2N8mzRgFZlfs2HKFJLL5ujF628MOEpqbbYa/7F4eTRixin2QxO9rAYf4ZShg9LnLuaQZVLxogjgl31WLyoNAxgpA7uAnAlzbu4BnYCkWLSkFY9Or1sBBn+48vTomP6CrX5yw7K+0KzMLPOFfV6tfaoEkAu8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
